// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package buildtags

import "fmt"

func MyThingPrint(t MyThing) {
	if t.Number > 0 {
		fmt.Println(t)
	}
}
