// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package buildtags

import "fmt"

type MyThing struct {
	Number int
}

func MyThingPrint(t MyThing) {
	fmt.Println(t)
}
